### PR TITLE
Update heroicons generator for v2

### PR DESCRIPTION
**Pull request by f0rest8**
Update to the heroicons generator. Would also need to update documentation as some name changes (e.g. "mail" -> "envelope"). I just separated into two functions, `loop_directory/1` and `loop_mini_directory/1`. I imagine you probably want to streamline it a bit? 😊

By updating your existing generator, you can keep your same functionality:

```elixir
# 24
<PetalComponents.Heroicons.Solid.home class="w-5 h-5" />
<PetalComponents.Heroicons.Solid.home title="Optional title for accessibility" class="w-5 h-5" />
<PetalComponents.Heroicons.Solid.render icon="home" class="w-5 h-5" />

<PetalComponents.Heroicons.Outline.home class="w-6 h-6" />
<PetalComponents.Heroicons.Outline.home title="Optional title for accessibility" class="w-6 h-6" />
<PetalComponents.Heroicons.Outline.render icon="home" class="w-6 h-6" />

# 20 (Mini)
<PetalComponents.Heroicons.Mini.Solid.home class="w-5 h-5" />
<PetalComponents.Heroicons.Mini.Solid.home title="Optional title for accessibility" class="w-5 h-5" />
<PetalComponents.Heroicons.Mini.Solid.render icon="home" class="w-5 h-5" />

<PetalComponents.Heroicons.Mini.Outline.home class="w-6 h-6" />
<PetalComponents.Heroicons.Mini.Outline.home title="Optional title for accessibility" class="w-6 h-6" />
<PetalComponents.Heroicons.Mini.Outline.render icon="home" class="w-6 h-6" />
```

### CODE REVIEW

**Review by mplatts — CHANGES_REQUESTED** [review]
Maybe through a test in heroicons_test.exs for the mini icon?

**Comment by f0rest8** [comment]
Thanks! I updated and tested in the Petal Development umbrella app. Just need to add a test now. 😊

**Comment by f0rest8** [comment]
Okay I think I cleaned up little typos, added tests for the `Heroicons.Mini.Solid`, updated tests that were calling v1 heroicons, and updated the `loop_directory/1` based on your suggestion. 

Although instead of multiple arguments, I went with one argument. Hmm... perhaps multiple arguments is preferable?

```elixir
# Looks like this:

Enum.each(
  [
    ["24/solid", "Solid", "solid"],
    ["24/outline", "Outline", "outline"],
    ["20/solid", "Mini.Solid", "mini/solid"]
  ],
  &loop_directory/1
)
```

**Comment by f0rest8** [comment]
Here's also the documentation for upgrading to v2. This might be useful to include the link and/or icon name change list in documentation for people: [Heroicons v2.0.0 Release Notes](https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0)

**Comment by mplatts** [comment]
Looking better, but now the variable name "folder" doesn't accurately label what it is.

Though after some thought I think it might be best to maybe shelve this PR and use another [Heroicons library](https://github.com/mveytsman/heroicons_elixir) as mentioned in this issue: https://github.com/petalframework/petal_components/issues/77

I feel bad as you have spent some time on this - but if we use this other library then perhaps it will save more time in future as it seems to be well maintained and saves us duplicating these upgrades. What do you think?

**Comment by f0rest8** [comment]
I agree and think it'd be better to drop and go with the Heroicons library. No worries, I enjoyed tinkering.

**Pull request closed without merging**
