### PR TITLE
Add `tooltip` to `<.button>`

### PR DESCRIPTION
**Pull request by fredwu**
Ported the same tooltip from `icon_button` to `button`.

### CODE REVIEW

**Comment by mplatts** [comment]
Sorry we do changelog stuff a bit different in Petal Components.. see instructions in release.exs. Just need to create a RELEASE.md file in the root dir

**Comment by fredwu** [comment]
Oh cool, do you want me to fix it up or are you doing it? :)

**Comment by mplatts** [comment]
I just added the RELEASE.md for your other PR - so maybe just pull the latest and move your changes off CHANGELOG into RELEASE

**Comment by fredwu** [comment]
Done!

**Comment by mplatts** [comment]
released in v1.2.3

**Comment by mplatts** [comment]
Had to revert this commit due to issues with icons in buttons:

CleanShot 2023-05-17 at 14 31 07@2x

**Comment by fredwu** [comment]
Oh whoops, let me take a look, will issue a new PR if I've got a fix.

**Pull request merged**
