### PR TITLE
Add `tooltip` to `<.button>`

### PR DESCRIPTION
**Pull request by fredwu**
Second attempt of #190.

Text only:

image

With loading:

image

With icon:

image

With icon and loading:

image

### CODE REVIEW

**Comment by mplatts** [comment]
Looking better! One thing I also missed last time is we don't put classes in the components anymore - we name classes using the BEM naming convention and put the CSS in `default.css`. This allows people to override it if they want. Couple of classes still in there if you want to have a go at a

**Comment by fredwu** [comment]
Done. The only exception is that the group class needs to stay in the markup per Tailwind:

> Groups can be named however you like and don’t need to be configured in any way — just name your groups directly in your markup and Tailwind will automatically generate the necessary CSS.

https://tailwindcss.com/docs/hover-focus-and-other-states#differentiating-nested-groups

**Comment by mplatts** [comment]
Didn't know that

**Comment by fredwu** [comment]
Closing in favour of simply using https://atomiks.github.io/tippyjs/ as suggested by @mplatts .

**Comment by mplatts** [comment]
( via https://petal.build/components/tooltip )

**Pull request closed without merging**
