### PR TITLE
New declarative assigns

### PR DESCRIPTION
**Pull request by nhobes**

### CODE REVIEW

**Comment by mohammedzeglam-pg** [comment]
thats is awesome but what about using this embedded pages

https://github.com/phoenixframework/phoenix_live_view/blob/cd93e0f3645d89b47d60a22eb8a085205d933df0/lib/phoenix_component.ex#L1386

**Comment by mplatts** [comment]
wow that's cool - hadn't seen that. How do you propose we use it in Petal Components? Could help with installing them.

**Comment by mohammedzeglam-pg** [comment]
> wow that's cool - hadn't seen that. How do you propose we use it in Petal Components? Could help with installing them.

https://github.com/mohammedzeglam-pg/e_commerce/blob/c869cdfa4bbeb234a654b5313c83b3d5b1d20eba/lib/e_commerce_web/shared/elements.ex#L1

**Comment by Rio517** [comment]
Looking forward to seeing this merged!

**Pull request merged**
