### PR TITLE
Feature: Allow groups in nested item

### PR DESCRIPTION
**Pull request by Gigitsu**
This allows the use of groups in nested menu items.

### CODE REVIEW

**Comment by mplatts** [comment]
Thanks! Can you provide a screenshot and also add a test?

**Comment by Gigitsu** [comment]
Sure! I will provide screenshots and a test asap.

**Comment by Gigitsu** [comment]
Hi @mplatts, I've added tests, tell me if they are enough.

Here are some screenshots:

- Open group (light and dark):
nested group open light
nested group open dark

- Closed group (light and dark):
nested group closed light
nested group closed dark

**Comment by Gigitsu** [comment]
This is how it is rendered, each nested group are separated by the same gap of the non nested groups

rendered wireframe

**Comment by Gigitsu** [comment]
Hi @mplatts, have you had the chance to check the updates?

**Comment by mplatts** [comment]
Hey sorry, been a bit swamped. Will take a look this weekend.

**Comment by Gigitsu** [comment]
Hi @mplatts, do you have any plan to merge this?

**Pull request closed without merging**
